"""add accounts table

Revision ID: 53df9aa975dd
Revises: cb959873d3fb
Create Date: 2026-10-08 06:08:19.133649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53df9aa975dd'
down_revision = 'cb959873d3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("account_type IN ('checking', 'savings')", name='ck_accounts_type'),
    sa.CheckConstraint('balance >= 0', name='ck_accounts_balance_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_type', 'currency', name='uq_accounts_user_type_currency')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
