"""add account balance events

Revision ID: 9342563b69f1
Revises: 53df9aa975dd
Create Date: 2026-10-09 19:16:57.875302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9342563b69f1'
down_revision = '53df9aa975dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("\n            (\n                event_type = 'opening'\n                AND balance_before IS NULL\n                AND amount >= 0\n                AND balance_after = amount\n            )\n            OR\n            (\n                event_type = 'correction'\n                AND balance_before IS NOT NULL\n                AND balance_after = balance_before + amount\n            )\n            ", name='ck_balance_events_consistency'),
    sa.CheckConstraint("event_type IN ('opening', 'correction')", name='ck_balance_events_type'),
    sa.CheckConstraint('balance_after >= 0', name='ck_balance_events_after_nonnegative'),
    sa.CheckConstraint('balance_before IS NULL OR balance_before >= 0', name='ck_balance_events_before_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_balance_events', schema=None) as batch_op:
        batch_op.create_index('uq_balance_events_one_opening_per_account', ['account_id'], unique=True, sqlite_where=sa.text("event_type = 'opening'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_balance_events', schema=None) as batch_op:
        batch_op.drop_index('uq_balance_events_one_opening_per_account', sqlite_where=sa.text("event_type = 'opening'"))

    op.drop_table('account_balance_events')
    # ### end Alembic commands ###
